// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringWSImpl.java.vsl in andromda-webservices.
//
package bw.ac.ub.cs.programme.service;

import bw.ac.ub.cs.programme.vo.ProgrammeVO;
import java.util.Collection;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/programme")
@CrossOrigin()
public class ProgrammeRestControllerImpl extends ProgrammeRestControllerBase {

    @Override
    public void handleDelete(Long id) {
    }

    @Override
    public ProgrammeVO handleFindById(Long id) {
    }

    @Override
    public Collection<ProgrammeVO> handleLoadAll() {
    }

    @Override
    public ProgrammeVO handleSave(ProgrammeVO programmeVO) {
    }

    @Override
    public ProgrammeVO handleSearch(String code, String name) {
    }

}