// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 05/28/2021 06:26:29+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.ac.ub.cs.programme;

import bw.ac.ub.cs.programme.vo.ProgrammeVO;
import org.springframework.stereotype.Repository;

/**
 * @see Programme
 */
@Repository("programmeDao")
public class ProgrammeDaoImpl
    extends ProgrammeDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toProgrammeVO(
        Programme source,
        ProgrammeVO target)
    {
        // TODO verify behavior of toProgrammeVO
        super.toProgrammeVO(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgrammeVO toProgrammeVO(final Programme entity)
    {
        // TODO verify behavior of toProgrammeVO
        return super.toProgrammeVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private Programme loadProgrammeFromProgrammeVO(ProgrammeVO programmeVO)
    {

        if (programmeVO.getId() == null)
        {
            return  Programme.Factory.newInstance();
        }
        else
        {
            return this.load(programmeVO.getId());
        }
    }

    /**
     * {@inheritDoc}
     */
    public Programme programmeVOToEntity(ProgrammeVO programmeVO)
    {
        // TODO verify behavior of programmeVOToEntity
        Programme entity = this.loadProgrammeFromProgrammeVO(programmeVO);
        this.programmeVOToEntity(programmeVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void programmeVOToEntity(
        ProgrammeVO source,
        Programme target,
        boolean copyIfNull)
    {
        // TODO verify behavior of programmeVOToEntity
        super.programmeVOToEntity(source, target, copyIfNull);
    }
}