// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditProgrammeComponent } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeSearchForm } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeSaveForm } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeNewForm } from '@app/view/web/programme/edit-programme.component';

@Component({
  selector: 'edit-programme',
  templateUrl: './edit-programme.component.html',
  styleUrls: ['./edit-programme.component.scss'],
})
export class EditProgrammeComponentImpl extends EditProgrammeComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  beforeOnInit() {}

  afterOnInit() {
    if (this.programmeController?.pageVariables?.id) {
      const id: number = this.programmeController?.pageVariables?.id;
      this.programmeRestController.findById(id).subscribe((programme) => {
        this.setEditProgrammeSaveForm({ programme });
      });
    }
  }

  doNgAfterViewInit() {}

  handleFormChanges(change: any) {}

  afterSetEditProgrammeSearchForm(form: EditProgrammeSearchForm): void {}

  afterEditProgrammeSearch(form: EditProgrammeSearchForm) {}

  beforeEditProgrammeSearch(form: EditProgrammeSearchForm) {}

  afterSetEditProgrammeSaveForm(form: EditProgrammeSaveForm): void {}

  afterEditProgrammeSave(form: EditProgrammeSaveForm) {}

  beforeEditProgrammeSave(form: EditProgrammeSaveForm) {}

  afterSetEditProgrammeNewForm(form: EditProgrammeNewForm): void {}

  afterEditProgrammeNew(form: EditProgrammeNewForm) {}

  beforeEditProgrammeNew(form: EditProgrammeNewForm) {}
}
