// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditProgrammeComponent } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeSearchForm } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeSaveForm } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeNewForm } from '@app/view/web/programme/edit-programme.component';
import { EditProgrammeVarsForm } from '@app/view/web/programme/edit-programme.component';

@Component({
  selector: 'edit-programme',
  templateUrl: './edit-programme.component.html',
  styleUrls: ['./edit-programme.component.scss']
})
export class EditProgrammeComponentImpl extends EditProgrammeComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
      
    }

    handleFormChanges(change: any) {
    }

    afterSetEditProgrammeSearchForm(form: EditProgrammeSearchForm): void {
    }

    afterEditProgrammeSearchEvent(form: EditProgrammeSearchForm) {    
    }

    beforeEditProgrammeSearchEvent(form: EditProgrammeSearchForm) {
    }

    afterSetEditProgrammeSaveForm(form: EditProgrammeSaveForm): void {
    }

    afterEditProgrammeSaveEvent(form: EditProgrammeSaveForm) {    
    }

    beforeEditProgrammeSaveEvent(form: EditProgrammeSaveForm) {
    }

    afterSetEditProgrammeNewForm(form: EditProgrammeNewForm): void {
    }

    afterEditProgrammeNewEvent(form: EditProgrammeNewForm) {    
    }

    beforeEditProgrammeNewEvent(form: EditProgrammeNewForm) {
    }

    afterSetEditProgrammeVarsForm(form: EditProgrammeVarsForm): void {
    }
}