// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { ProgrammeComponent } from '@app/view/web/programme/programme.component';
import { ProgrammeEditForm } from '@app/view/web/programme/programme.component';
import { ProgrammeSearchForm } from '@app/view/web/programme/programme.component';
import { ProgrammeDeleteForm } from '@app/view/web/programme/programme.component';

@Component({
  selector: 'programme',
  templateUrl: './programme.component.html',
  styleUrls: ['./programme.component.scss']
})
export class ProgrammeComponentImpl extends ProgrammeComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
      
    }

    handleFormChanges(change: any) {
    }

    afterSetProgrammeEditForm(form: ProgrammeEditForm): void {
    }

    afterProgrammeEditEvent(form: ProgrammeEditForm) {    
    }

    beforeProgrammeEditEvent(form: ProgrammeEditForm) {
    }

    afterSetProgrammeSearchForm(form: ProgrammeSearchForm): void {
    }

    afterProgrammeSearchEvent(form: ProgrammeSearchForm) {    
    }

    beforeProgrammeSearchEvent(form: ProgrammeSearchForm) {
    }

    afterSetProgrammeDeleteForm(form: ProgrammeDeleteForm): void {
    }

    afterProgrammeDeleteEvent(form: ProgrammeDeleteForm) {    
    }

    beforeProgrammeDeleteEvent(form: ProgrammeDeleteForm) {
    }

}