// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchProgrammesComponent } from '@app/view/web/programme/search-programmes.component';
import { SearchProgrammesSearchForm } from '@app/view/web/programme/search-programmes.component';
import { SearchProgrammesProgrammeForm } from '@app/view/web/programme/search-programmes.component';

@Component({
  selector: 'search-programmes',
  templateUrl: './search-programmes.component.html',
  styleUrls: ['./search-programmes.component.scss'],
})
export class SearchProgrammesComponentImpl extends SearchProgrammesComponent {
  constructor(private injector: Injector) {
    super(injector);
  }

  beforeOnInit() {}

  afterOnInit() {
    this.programmeRestController.loadAll().subscribe((programmes) => {
      this.setProgrammes(programmes);
    });
  }

  doNgAfterViewInit() {}

  handleFormChanges(change: any) {}

  afterSetSearchProgrammesSearchForm(form: SearchProgrammesSearchForm): void {}

  afterSearchProgrammesSearch(form: SearchProgrammesSearchForm) {}

  beforeSearchProgrammesSearch(form: SearchProgrammesSearchForm) {}

  afterSetSearchProgrammesProgrammeForm(form: SearchProgrammesProgrammeForm): void {}

  afterSearchProgrammesProgramme(form: SearchProgrammesProgrammeForm) {}

  beforeSearchProgrammesProgramme(form: SearchProgrammesProgrammeForm) {}
}
