// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, Injector } from '@angular/core';
import { HttpClient} from '@angular/common/http';
import { Observable } from 'rxjs';
import { ProgrammeRestController } from '@app/service/bw/ac/ub/cs/programme/service/programme-rest-controller';
import { ProgrammeVO } from '@app/${import.filePath}';

@Injectable()
export class ProgrammeRestControllerImpl extends ProgrammeRestController {

    constructor(private injector: Injector) {
        super(injector);
    }

    public delete(id: number): Observable<void> {

        return this.http.delete<void>(this.path + "/" + "/id/" + id + "/");

    }

    public findById(id: number): Observable<ProgrammeVO> {

        return this.http.get<ProgrammeVO>(this.path + "/" + "/id/" + id + "/");

    }

    public loadAll(): Observable<ProgrammeVO[]> {

        return this.http.get<ProgrammeVO[]>(this.path + "/" + "/");

    }

    public save(programmeVO: ProgrammeVO): Observable<ProgrammeVO> {

        let formData: any = new FormData();
        formData = programmeVO;
        return this.http.post<ProgrammeVO>(this.path + "/" + "/", formData);

    }

    public search(code: string, name: string): Observable<ProgrammeVO> {

        let formData: any = new FormData();
        formData.append("code", code)
        formData.append("name", name)
        return this.http.post<ProgrammeVO>(this.path + "/search" + "/", formData);

    }

}